export const translations = {
  fr: {
    settings: "Réglages",
    appearance: "Apparence",
    darkMode: "Mode sombre",
    language: "Langue",
    admissionTitle: "PARCOURS ET PROCÉDURE D'ADMISSION",
    admissionIntro: "L'ESISA sélectionne les meilleurs talents pour former l'élite en ingénierie informatique.",
    admissionDescription1: "À l'ESISA, nous croyons que ",
    highlightMotivation: "la motivation",
    and: "et",
    highlightPassion: "la passion pour le numérique",
    admissionDescription2: " sont les moteurs de l'excellence. Nous recherchons des étudiants déterminés, prêts à façonner le monde de demain grâce aux technologies innovantes. Chaque candidature est évaluée avec soin en tenant compte de :",
    criteria: [
      { title: "Motivation et Ambition", description: "Votre détermination à réussir et à innover est essentielle." },
      { title: "Note en Mathématiques et Français au Bac", description: "Indicateurs clés de réussite." },
      { title: "Si les notes sont insuffisantes", description: "Un test de Mathématiques est requis." },
      { title: "Entretien de motivation", description: "Pour évaluer votre passion, vos objectifs et votre vision." },
    ],
    admissionConclusion: "Nous privilégions les profils engagés et motivés, capables de relever les défis technologiques de demain.",
    processTitle: "Étapes du processus d'admission",
    processSteps: [
      { title: "Soumission du dossier", description: "Formulaire d'inscription complété, copie de la CIN, relevés de notes du Bac, photo d'identité récente" },
      { title: "Étude du dossier académique", description: "Analyse des notes en mathématiques et français, vérification du profil académique" },
      { title: "Test d'aptitude (si nécessaire)", description: "Test de mathématiques pour les candidats dont les notes au Bac sont insuffisantes" },
      { title: "Entretien de motivation", description: "Discussion approfondie sur vos objectifs, votre passion pour l'informatique et votre vision du futur numérique" },
      { title: "Décision d'admission", description: "Notification par email et courrier dans un délai de 7 jours après l'entretien" },
    ],
    profilesTitle: "Profils admissibles",
    profiles: [
      { title: "Accès en 1ère année", description: "Bac Scientifique, Économique et Technique" },
      { title: "Accès en 2ème année", description: "CPGE, Math Spé, EST, BTS, DUT ou Diplôme Équivalent" },
      { title: "Accès en M1", description: "Licence en Informatique ou Diplôme Équivalent" },
    ],
    datesTitle: "Dates importantes",
    dates: [
      { date: "1er Décembre - 30 Avril", description: "Période de dépôt des candidatures pour l'année académique suivante" },
      { date: "Mai - Juin", description: "Sessions d'entretiens et tests d'admission" },
      { date: "15 Juillet", description: "Date limite de confirmation d'inscription pour les candidats admis" },
      { date: "Septembre", description: "Rentrée académique et semaine d'intégration" },
    ],
    contactTitle: "Besoin d'informations supplémentaires ?",
    contacts: [
      { icon: "mail", text: "admission@esisa.ma" },
      { icon: "phone", text: "+212 5 22 27 22 42" },
      { icon: "location-on", text: "282, Boulevard Zerktouni, Casablanca, Maroc" },
    ],
    applyNow: "POSTULER MAINTENANT",
    internationalTitle: "L'ESISA ET L'INTERNATIONAL",
    internationalIntro:
      "🚀 Une formation tournée vers l’international : L'ESISA ouvre à ses étudiants les portes d’une carrière mondiale grâce à ses partenariats avec des institutions de renom en France, aux États-Unis et au-delà. Nos programmes sont conçus pour offrir une expérience académique et professionnelle enrichissante.",
    internationalStagesTitle: "📅 STAGES À L'ÉTRANGER",
    internationalStagesDesc:
      "- 3ème année : Stage de 2 à 3 mois dans des entreprises partenaires.\n- 5ème année : Stage de 4 à 6 mois dans des secteurs innovants.",
    internationalSkillsTitle: "🧠 COMPÉTENCES LINGUISTIQUES",
    internationalSkillsDesc:
      "- Préparation avancée au TOEIC pour une maîtrise de l’anglais professionnel.\n- Certification B2/C1 en français grâce à notre partenariat avec l’Institut Français.",
    internationalCareersTitle: "🌍 CARRIÈRES GLOBALES",
    internationalCareersDesc:
      "Chaque année, nos étudiants poursuivent leurs études dans des établissements de prestige ou débutent leur carrière dans des environnements internationaux.\nPour l’année universitaire 2025/2026, 95% de nos étudiants de master 1 IS2IA ont intégré des masters dans des universités prestigieuses et des écoles d’ingénieurs d’État en France.",
    internationalAdmittedTitle: "🌎 ADMIS À L'ÉTRANGER",
    internationalAdmittedDesc:
      "Chaque année, une grande partie des étudiants de la 4ème année continuent leurs études en France, soit avec nos partenaires, soit dans d'autres universités étrangères.\nL’année universitaire 2024/2025, 95% des étudiants ont été acceptés dans nos universités et écoles partenaires.",
    internationalPartnersTitle: "NOS PARTENAIRES EN FRANCE",
    internationalAddressLabel: "ADRESSE",
    internationalAddress: "29 Bis Av Ibn Khatib Route d’Imouzzer, Fès-Maroc",
    internationalPhoneLabel: "TÉLÉPHONE",
    internationalPhone: "+212 (0)6 61 45 35 09",
    internationalEmailLabel: "EMAIL",
    internationalEmail: "info@esisa.ac.ma",

     coursesTitle: "Nos Formations",
    coursesIntro: "L'enseignement à l'école ESISA est fondé sur un fonctionnement par semestre, basé sur le système modulaire. À l'école ESISA, l'enseignement est dispensé en 2 cycles étalés sur 5 années d'études.",
    firstCycleTitle: "1er Cycle (Bac +3 ans)",
    years12Title: "1ère et 2ème années",
    years12Description: "L'objectif est d'initier l'étudiant aux domaines de l'informatique avec ses différentes disciplines, et de développer ses compétences en développement informatique à travers une formation centrée sur:",
    years12Subjects: [
      "Programmation",
      "Structures de données",
      "Langages de programmation",
      "Bases de données",
      "Systèmes d'information",
      "Réseaux informatiques"
    ],
    year3Title: "3ème année",
    year3Description: "L'objectif est de former des assistants débutants à la maîtrise d'œuvre (MOE) et à la maîtrise d'ouvrage (MO), dans les domaines de la conception et de l'administration des systèmes d'information:",
    year3Subjects: [
      "Bases de données",
      "Réseaux",
      "Architecture technique",
      "Développement d'applications",
      "Déploiement logiciel",
      "Intégration d'exploitation",
      "Analyse et traitements statistiques"
    ],
    secondCycleTitle: "2ème Cycle (2 ans après Bac +3)",
    years45Title: "4ème et 5ème années",
    years45Description1: "Ce cycle comprend 2 années d'études. Il a pour objectif principal de faire évoluer les compétences de l'étudiant vers la maîtrise des grands systèmes et leurs architectures, avec une grande expérience théorique et technique dans le domaine du développement basé sur les nouvelles technologies informatiques.",
    years45Description2: "Il se clôt par la réalisation d'un projet de fin d'études dans le secteur industriel, mené principalement au sein des entreprises actives dans le développement informatique à l'échelle internationale et dans le domaine du développement offshore.",
    years45Description3: "Options disponibles:",
    years45Options: [
      "M1 et M2 à l'ESISA",
      "M2 dans des universités étatiques en France suite au M1 à l'ESISA",
      "Diplôme d'Ingénieur d'état en France (2 ans)"
    ],
    languageSectionTitle: "Importance des langues",
    languageSectionDesc1: "L'école ESISA met l'accent sur l'importance de la communication en français et en anglais dans les métiers de l'ingénierie. Tout au long des années d'études, les étudiants sont préparés à une meilleure adaptation linguistique pour faciliter leur intégration dans les cursus finaux à l'étranger et ouvrir les portes des métiers de l'avenir.",
    languageSectionDesc2: "En outre, les entretiens de sélection pour les différentes écoles et universités partenaires se passent en français et en anglais. Les étudiants de l'ESISA sont appelés à atteindre le niveau de TOEIC (Test Of English for International Communication) en fin de 4ème année."
  


  },error: "Erreur",
  documentSelectError: "Impossible de sélectionner le document",
  enterNamePrenom: "Veuillez saisir votre nom et prénom",
  enterValidEmail: "Veuillez saisir une adresse email valide",
  enterValidPhone: "Veuillez saisir un numéro de téléphone valide (format marocain)",
  enterBirthdate: "Veuillez saisir votre date de naissance",
  selectNiveau: "Veuillez sélectionner le niveau d'entrée souhaité",
  enterBacNotes: "Veuillez saisir vos notes de mathématiques et de français au baccalauréat",
  attachCin: "Veuillez joindre une copie de votre CIN",
  attachRelevesBac: "Veuillez joindre vos relevés de notes du baccalauréat",
  attachPhoto: "Veuillez joindre une photo d'identité récente",
  sendError: "Une erreur est survenue lors de l'envoi.",
  submitFormError: "Une erreur est survenue lors de l'envoi de votre candidature. Veuillez réessayer ultérieurement.",
  applicationFormTitle: "FORMULAIRE DE CANDIDATURE",
  applicationFormIntro: "Complétez ce formulaire pour soumettre votre candidature à l'ESISA",
  personalInformation: "Informations Personnelles",
  lastName: "Nom",
  firstName: "Prénom",
  email: "Email",
  phone: "Téléphone",
  birthDate: "Date de naissance",
  address: "Adresse",
  city: "Ville",
  academicInformation: "Informations Académiques",
  desiredLevel: "Niveau d'entrée souhaité",
  selectLevelPlaceholder: "Sélectionnez un niveau...",
  firstYear: "1ère année",
  secondYear: "2ème année",
  thirdYear: "3ème année",
  master1: "Master 1 (M1)",
  master2: "Master 2 (M2)",
  fieldOfStudy: "Filière (si applicable)",
  enterFieldOfStudy: "Filière souhaitée",
  mathBac: "Note en Mathématiques au Bac",
  enterMathNote: "Votre note en mathématiques",
  frenchBac: "Note en Français au Bac",
  enterFrenchNote: "Votre note en français",
  generalAvgBac: "Moyenne générale au Bac",
  enterGeneralAvg: "Votre moyenne générale",
  requiredDocuments: "Documents Requis",
  cinCopy: "Copie de la CIN (recto/verso)",
  cinDesc: "Format PDF ou image (max 5 Mo)",
  bacRecords: "Relevés de notes du Bac",
  bacRecordsDesc: "Format PDF ou image (max 5 Mo)",
  recentPhoto: "Photo d'identité récente",
  recentPhotoDesc: "Format JPEG ou PNG (max 2 Mo)",
  modify: "Modifier",
  choose: "Choisir",
  fileSelected: "Fichier sélectionné",
  motivationLetter: "Lettre de Motivation",
  motivationPlaceholder: "Expliquez brièvement votre motivation à rejoindre l'ESISA (min. 100 caractères)",
  submitApplication: "ENVOYER MA CANDIDATURE",
  mandatoryFields: "* Champs obligatoires",
  applicationSent: "Candidature Envoyée !",
  applicationSentDesc: "Votre candidature a été envoyée avec succès. Nous vous contacterons prochainement.",
  en: {
    settings: "Settings",
    appearance: "Appearance",
    darkMode: "Dark Mode",
    language: "Language",
    admissionTitle: "ADMISSION PROCESS AND PROCEDURE",
    admissionIntro: "ESISA selects the best talents to train the elite in computer engineering.",
    admissionDescription1: "At ESISA, we believe that ",
    highlightMotivation: "motivation",
    and: "and",
    highlightPassion: "passion for digital technology",
    admissionDescription2: " are the driving forces of excellence. We look for determined students ready to shape tomorrow’s world through innovative technologies. Each application is carefully evaluated taking into account:",
    criteria: [
      { title: "Motivation and Ambition", description: "Your determination to succeed and innovate is essential." },
      { title: "Grades in Mathematics and French at the Bac", description: "Key indicators of success." },
      { title: "If grades are insufficient", description: "A Mathematics test is required." },
      { title: "Motivational Interview", description: "To assess your passion, goals, and vision." },
    ],
    admissionConclusion: "We favor engaged and motivated profiles capable of meeting tomorrow’s technological challenges.",
    processTitle: "Steps of the Admission Process",
    processSteps: [
      { title: "Submission of Application", description: "Completed registration form, copy of ID card, Bac transcripts, recent ID photo" },
      { title: "Academic File Review", description: "Analysis of grades in mathematics and French, verification of academic profile" },
      { title: "Aptitude Test (if necessary)", description: "Mathematics test for candidates whose Bac grades are insufficient" },
      { title: "Motivational Interview", description: "In-depth discussion about your goals, passion for computing, and vision for the digital future" },
      { title: "Admission Decision", description: "Notification by email and mail within 7 days after the interview" },
    ],
    profilesTitle: "Eligible Profiles",
    profiles: [
      { title: "Access to 1st Year", description: "Scientific, Economic, and Technical Bac" },
      { title: "Access to 2nd Year", description: "CPGE, Math Specialization, EST, BTS, DUT or Equivalent Diploma" },
      { title: "Access to M1", description: "Bachelor’s Degree in Computer Science or Equivalent Diploma" },
    ],
    datesTitle: "Important Dates",
    dates: [
      { date: "December 1 - April 30", description: "Application submission period for the following academic year" },
      { date: "May - June", description: "Interview and admission test sessions" },
      { date: "July 15", description: "Deadline for confirming registration for admitted candidates" },
      { date: "September", description: "Academic start and integration week" },
    ],
    contactTitle: "Need more information?",
    contacts: [
      { icon: "mail", text: "admission@esisa.ma" },
      { icon: "phone", text: "+212 5 22 27 22 42" },
      { icon: "location-on", text: "282, Boulevard Zerktouni, Casablanca, Morocco" },
    ],
    applyNow: "APPLY NOW",

    internationalTitle: "ESISA AND INTERNATIONAL",
    internationalIntro:
      "🚀 A globally oriented training: ESISA opens the doors of a worldwide career to its students thanks to partnerships with renowned institutions in France, the United States, and beyond. Our programs are designed to offer an enriching academic and professional experience.",
    internationalStagesTitle: "📅 INTERNSHIPS ABROAD",
    internationalStagesDesc:
      "- 3rd year: 2 to 3 months internship in partner companies.\n- 5th year: 4 to 6 months internship in innovative sectors.",
    internationalSkillsTitle: "🧠 LANGUAGE SKILLS",
    internationalSkillsDesc:
      "- Advanced TOEIC preparation for mastering professional English.\n- B2/C1 French certification thanks to our partnership with the Institut Français.",
    internationalCareersTitle: "🌍 GLOBAL CAREERS",
    internationalCareersDesc:
      "Every year, our students continue their studies at prestigious institutions or start their careers in international environments.\nFor the 2025/2026 academic year, 95% of our Master 1 IS2IA students joined master's programs at prestigious universities and state engineering schools in France.",
    internationalAdmittedTitle: "🌎 ADMITTED ABROAD",
    internationalAdmittedDesc:
      "Each year, a large part of 4th-year students continue their studies in France, either with our partners or in other foreign universities.\nIn the 2024/2025 academic year, 95% of students were accepted in our partner universities and schools.",
    internationalPartnersTitle: "OUR PARTNERS IN FRANCE",
    internationalAddressLabel: "ADDRESS",
    internationalAddress: "29 Bis Av Ibn Khatib Route d’Imouzzer, Fès, Morocco",
    internationalPhoneLabel: "PHONE",
    internationalPhone: "+212 (0)6 61 45 35 09",
    internationalEmailLabel: "EMAIL",
    internationalEmail: "info@esisa.ac.ma",


     coursesTitle: "Our Courses",
    coursesIntro: "The teaching at ESISA is based on a semester system and modular courses. ESISA provides education in 2 cycles spread over 5 years.",
    firstCycleTitle: "First Cycle (Bac +3 years)",
    years12Title: "1st and 2nd Years",
    years12Description: "The goal is to introduce students to different fields of computer science and develop their skills in software development with training focused on:",
    years12Subjects: [
      "Programming",
      "Data Structures",
      "Programming Languages",
      "Databases",
      "Information Systems",
      "Computer Networks"
    ],
    year3Title: "3rd Year",
    year3Description: "The goal is to train beginner assistants in project management (MOE) and project ownership (MO) in the fields of design and administration of information systems:",
    year3Subjects: [
      "Databases",
      "Networks",
      "Technical Architecture",
      "Application Development",
      "Software Deployment",
      "Operation Integration",
      "Statistical Analysis and Processing"
    ],
    secondCycleTitle: "Second Cycle (2 years after Bac +3)",
    years45Title: "4th and 5th Years",
    years45Description1: "This cycle consists of 2 years of studies. Its main goal is to develop the student's skills towards mastering large systems and their architectures, with extensive theoretical and technical experience in development based on new IT technologies.",
    years45Description2: "It concludes with a final project mainly carried out within companies active in international software development and offshore development.",
    years45Description3: "Available options:",
    years45Options: [
      "M1 and M2 at ESISA",
      "M2 in state universities in France after M1 at ESISA",
      "State Engineering Degree in France (2 years)"
    ],
    languageSectionTitle: "Importance of Languages",
    languageSectionDesc1: "ESISA emphasizes the importance of communication in French and English in engineering professions. Throughout the years of study, students are prepared for better linguistic adaptation to facilitate integration in final courses abroad and open the doors to future professions.",
    languageSectionDesc2: "Additionally, the selection interviews for different partner schools and universities are conducted in French and English. ESISA students are expected to reach TOEIC (Test Of English for International Communication) level by the end of the 4th year.",
  
error: "Error",
  documentSelectError: "Unable to select the document",
  enterNamePrenom: "Please enter your last and first name",
  enterValidEmail: "Please enter a valid email address",
  enterValidPhone: "Please enter a valid phone number (Moroccan format)",
  enterBirthdate: "Please enter your birth date",
  selectNiveau: "Please select the desired entry level",
  enterBacNotes: "Please enter your math and French grades at the baccalaureate",
  attachCin: "Please attach a copy of your CIN",
  attachRelevesBac: "Please attach your baccalaureate transcripts",
  attachPhoto: "Please attach a recent ID photo",
  sendError: "An error occurred during submission.",
  submitFormError: "An error occurred while sending your application. Please try again later.",
  applicationFormTitle: "APPLICATION FORM",
  applicationFormIntro: "Fill in this form to submit your application to ESISA",
  personalInformation: "Personal Information",
  lastName: "Last Name",
  firstName: "First Name",
  email: "Email",
  phone: "Phone",
  birthDate: "Birth Date",
  address: "Address",
  city: "City",
  academicInformation: "Academic Information",
  desiredLevel: "Desired Entry Level",
  selectLevelPlaceholder: "Select a level...",
  firstYear: "1st Year",
  secondYear: "2nd Year",
  thirdYear: "3rd Year",
  master1: "Master 1 (M1)",
  master2: "Master 2 (M2)",
  fieldOfStudy: "Field of Study (if applicable)",
  enterFieldOfStudy: "Desired field of study",
  mathBac: "Math grade at Bac",
  enterMathNote: "Your math grade",
  frenchBac: "French grade at Bac",
  enterFrenchNote: "Your French grade",
  generalAvgBac: "General average at Bac",
  enterGeneralAvg: "Your general average",
  requiredDocuments: "Required Documents",
  cinCopy: "Copy of CIN (front/back)",
  cinDesc: "PDF or image format (max 5 MB)",
  bacRecords: "Bac transcripts",
  bacRecordsDesc: "PDF or image format (max 5 MB)",
  recentPhoto: "Recent ID photo",
  recentPhotoDesc: "JPEG or PNG format (max 2 MB)",
  modify: "Modify",
  choose: "Choose",
  fileSelected: "File selected",
  motivationLetter: "Motivation Letter",
  motivationPlaceholder: "Briefly explain your motivation to join ESISA (min. 100 characters)",
  submitApplication: "SUBMIT MY APPLICATION",
  mandatoryFields: "* Mandatory fields",
  applicationSent: "Application Sent!",
  applicationSentDesc: "Your application has been sent successfully. We will contact you soon.",
  }
};