export const translations = {
  fr: {
    settings: "Réglages",
    appearance: "Apparence",
    darkMode: "Mode sombre",
    language: "Langue",
    admissionTitle: "PARCOURS ET PROCÉDURE D'ADMISSION",
    admissionIntro: "L'ESISA sélectionne les meilleurs talents pour former l'élite en ingénierie informatique.",
    admissionDescription1: "À l'ESISA, nous croyons que ",
    highlightMotivation: "la motivation",
    and: "et",
    highlightPassion: "la passion pour le numérique",
    admissionDescription2: " sont les moteurs de l'excellence. Nous recherchons des étudiants déterminés, prêts à façonner le monde de demain grâce aux technologies innovantes. Chaque candidature est évaluée avec soin en tenant compte de :",
    criteria: [
      { title: "Motivation et Ambition", description: "Votre détermination à réussir et à innover est essentielle." },
      { title: "Note en Mathématiques et Français au Bac", description: "Indicateurs clés de réussite." },
      { title: "Si les notes sont insuffisantes", description: "Un test de Mathématiques est requis." },
      { title: "Entretien de motivation", description: "Pour évaluer votre passion, vos objectifs et votre vision." },
    ],
    admissionConclusion: "Nous privilégions les profils engagés et motivés, capables de relever les défis technologiques de demain.",
    processTitle: "Étapes du processus d'admission",
    processSteps: [
      { title: "Soumission du dossier", description: "Formulaire d'inscription complété, copie de la CIN, relevés de notes du Bac, photo d'identité récente" },
      { title: "Étude du dossier académique", description: "Analyse des notes en mathématiques et français, vérification du profil académique" },
      { title: "Test d'aptitude (si nécessaire)", description: "Test de mathématiques pour les candidats dont les notes au Bac sont insuffisantes" },
      { title: "Entretien de motivation", description: "Discussion approfondie sur vos objectifs, votre passion pour l'informatique et votre vision du futur numérique" },
      { title: "Décision d'admission", description: "Notification par email et courrier dans un délai de 7 jours après l'entretien" },
    ],
    profilesTitle: "Profils admissibles",
    profiles: [
      { title: "Accès en 1ère année", description: "Bac Scientifique, Économique et Technique" },
      { title: "Accès en 2ème année", description: "CPGE, Math Spé, EST, BTS, DUT ou Diplôme Équivalent" },
      { title: "Accès en M1", description: "Licence en Informatique ou Diplôme Équivalent" },
    ],
    datesTitle: "Dates importantes",
    dates: [
      { date: "1er Décembre - 30 Avril", description: "Période de dépôt des candidatures pour l'année académique suivante" },
      { date: "Mai - Juin", description: "Sessions d'entretiens et tests d'admission" },
      { date: "15 Juillet", description: "Date limite de confirmation d'inscription pour les candidats admis" },
      { date: "Septembre", description: "Rentrée académique et semaine d'intégration" },
    ],
    contactTitle: "Besoin d'informations supplémentaires ?",
    contacts: [
      { icon: "mail", text: "admission@esisa.ma" },
      { icon: "phone", text: "+212 5 22 27 22 42" },
      { icon: "location-on", text: "282, Boulevard Zerktouni, Casablanca, Maroc" },
    ],
    applyNow: "POSTULER MAINTENANT",
    internationalTitle: "L'ESISA ET L'INTERNATIONAL",
    internationalIntro:
      "🚀 Une formation tournée vers l’international : L'ESISA ouvre à ses étudiants les portes d’une carrière mondiale grâce à ses partenariats avec des institutions de renom en France, aux États-Unis et au-delà. Nos programmes sont conçus pour offrir une expérience académique et professionnelle enrichissante.",
    internationalStagesTitle: "📅 STAGES À L'ÉTRANGER",
    internationalStagesDesc:
      "- 3ème année : Stage de 2 à 3 mois dans des entreprises partenaires.\n- 5ème année : Stage de 4 à 6 mois dans des secteurs innovants.",
    internationalSkillsTitle: "🧠 COMPÉTENCES LINGUISTIQUES",
    internationalSkillsDesc:
      "- Préparation avancée au TOEIC pour une maîtrise de l’anglais professionnel.\n- Certification B2/C1 en français grâce à notre partenariat avec l’Institut Français.",
    internationalCareersTitle: "🌍 CARRIÈRES GLOBALES",
    internationalCareersDesc:
      "Chaque année, nos étudiants poursuivent leurs études dans des établissements de prestige ou débutent leur carrière dans des environnements internationaux.\nPour l’année universitaire 2025/2026, 95% de nos étudiants de master 1 IS2IA ont intégré des masters dans des universités prestigieuses et des écoles d’ingénieurs d’État en France.",
    internationalAdmittedTitle: "🌎 ADMIS À L'ÉTRANGER",
    internationalAdmittedDesc:
      "Chaque année, une grande partie des étudiants de la 4ème année continuent leurs études en France, soit avec nos partenaires, soit dans d'autres universités étrangères.\nL’année universitaire 2024/2025, 95% des étudiants ont été acceptés dans nos universités et écoles partenaires.",
    internationalPartnersTitle: "NOS PARTENAIRES EN FRANCE",
    internationalAddressLabel: "ADRESSE",
    internationalAddress: "29 Bis Av Ibn Khatib Route d’Imouzzer, Fès-Maroc",
    internationalPhoneLabel: "TÉLÉPHONE",
    internationalPhone: "+212 (0)6 61 45 35 09",
    internationalEmailLabel: "EMAIL",
    internationalEmail: "info@esisa.ac.ma",
  },
  en: {
    settings: "Settings",
    appearance: "Appearance",
    darkMode: "Dark Mode",
    language: "Language",
    admissionTitle: "ADMISSION PROCESS AND PROCEDURE",
    admissionIntro: "ESISA selects the best talents to train the elite in computer engineering.",
    admissionDescription1: "At ESISA, we believe that ",
    highlightMotivation: "motivation",
    and: "and",
    highlightPassion: "passion for digital technology",
    admissionDescription2: " are the driving forces of excellence. We look for determined students ready to shape tomorrow’s world through innovative technologies. Each application is carefully evaluated taking into account:",
    criteria: [
      { title: "Motivation and Ambition", description: "Your determination to succeed and innovate is essential." },
      { title: "Grades in Mathematics and French at the Bac", description: "Key indicators of success." },
      { title: "If grades are insufficient", description: "A Mathematics test is required." },
      { title: "Motivational Interview", description: "To assess your passion, goals, and vision." },
    ],
    admissionConclusion: "We favor engaged and motivated profiles capable of meeting tomorrow’s technological challenges.",
    processTitle: "Steps of the Admission Process",
    processSteps: [
      { title: "Submission of Application", description: "Completed registration form, copy of ID card, Bac transcripts, recent ID photo" },
      { title: "Academic File Review", description: "Analysis of grades in mathematics and French, verification of academic profile" },
      { title: "Aptitude Test (if necessary)", description: "Mathematics test for candidates whose Bac grades are insufficient" },
      { title: "Motivational Interview", description: "In-depth discussion about your goals, passion for computing, and vision for the digital future" },
      { title: "Admission Decision", description: "Notification by email and mail within 7 days after the interview" },
    ],
    profilesTitle: "Eligible Profiles",
    profiles: [
      { title: "Access to 1st Year", description: "Scientific, Economic, and Technical Bac" },
      { title: "Access to 2nd Year", description: "CPGE, Math Specialization, EST, BTS, DUT or Equivalent Diploma" },
      { title: "Access to M1", description: "Bachelor’s Degree in Computer Science or Equivalent Diploma" },
    ],
    datesTitle: "Important Dates",
    dates: [
      { date: "December 1 - April 30", description: "Application submission period for the following academic year" },
      { date: "May - June", description: "Interview and admission test sessions" },
      { date: "July 15", description: "Deadline for confirming registration for admitted candidates" },
      { date: "September", description: "Academic start and integration week" },
    ],
    contactTitle: "Need more information?",
    contacts: [
      { icon: "mail", text: "admission@esisa.ma" },
      { icon: "phone", text: "+212 5 22 27 22 42" },
      { icon: "location-on", text: "282, Boulevard Zerktouni, Casablanca, Morocco" },
    ],
    applyNow: "APPLY NOW",

    internationalTitle: "ESISA AND INTERNATIONAL",
    internationalIntro:
      "🚀 A globally oriented training: ESISA opens the doors of a worldwide career to its students thanks to partnerships with renowned institutions in France, the United States, and beyond. Our programs are designed to offer an enriching academic and professional experience.",
    internationalStagesTitle: "📅 INTERNSHIPS ABROAD",
    internationalStagesDesc:
      "- 3rd year: 2 to 3 months internship in partner companies.\n- 5th year: 4 to 6 months internship in innovative sectors.",
    internationalSkillsTitle: "🧠 LANGUAGE SKILLS",
    internationalSkillsDesc:
      "- Advanced TOEIC preparation for mastering professional English.\n- B2/C1 French certification thanks to our partnership with the Institut Français.",
    internationalCareersTitle: "🌍 GLOBAL CAREERS",
    internationalCareersDesc:
      "Every year, our students continue their studies at prestigious institutions or start their careers in international environments.\nFor the 2025/2026 academic year, 95% of our Master 1 IS2IA students joined master's programs at prestigious universities and state engineering schools in France.",
    internationalAdmittedTitle: "🌎 ADMITTED ABROAD",
    internationalAdmittedDesc:
      "Each year, a large part of 4th-year students continue their studies in France, either with our partners or in other foreign universities.\nIn the 2024/2025 academic year, 95% of students were accepted in our partner universities and schools.",
    internationalPartnersTitle: "OUR PARTNERS IN FRANCE",
    internationalAddressLabel: "ADDRESS",
    internationalAddress: "29 Bis Av Ibn Khatib Route d’Imouzzer, Fès, Morocco",
    internationalPhoneLabel: "PHONE",
    internationalPhone: "+212 (0)6 61 45 35 09",
    internationalEmailLabel: "EMAIL",
    internationalEmail: "info@esisa.ac.ma",
  }
};

