export const translations = {
  fr: {
    settings: "Réglages",
    appearance: "Apparence",
    darkMode: "Mode sombre",
    language: "Langue",
    admissionTitle: "PARCOURS ET PROCÉDURE D'ADMISSION",
    admissionIntro: "L'ESISA sélectionne les meilleurs talents pour former l'élite en ingénierie informatique.",
    admissionDescription1: "À l'ESISA, nous croyons que ",
    highlightMotivation: "la motivation",
    and: "et",
    highlightPassion: "la passion pour le numérique",
    admissionDescription2: " sont les moteurs de l'excellence. Nous recherchons des étudiants déterminés, prêts à façonner le monde de demain grâce aux technologies innovantes. Chaque candidature est évaluée avec soin en tenant compte de :",
    criteria: [
      { title: "Motivation et Ambition", description: "Votre détermination à réussir et à innover est essentielle." },
      { title: "Note en Mathématiques et Français au Bac", description: "Indicateurs clés de réussite." },
      { title: "Si les notes sont insuffisantes", description: "Un test de Mathématiques est requis." },
      { title: "Entretien de motivation", description: "Pour évaluer votre passion, vos objectifs et votre vision." },
    ],
    admissionConclusion: "Nous privilégions les profils engagés et motivés, capables de relever les défis technologiques de demain.",
    processTitle: "Étapes du processus d'admission",
    processSteps: [
      { title: "Soumission du dossier", description: "Formulaire d'inscription complété, copie de la CIN, relevés de notes du Bac, photo d'identité récente" },
      { title: "Étude du dossier académique", description: "Analyse des notes en mathématiques et français, vérification du profil académique" },
      { title: "Test d'aptitude (si nécessaire)", description: "Test de mathématiques pour les candidats dont les notes au Bac sont insuffisantes" },
      { title: "Entretien de motivation", description: "Discussion approfondie sur vos objectifs, votre passion pour l'informatique et votre vision du futur numérique" },
      { title: "Décision d'admission", description: "Notification par email et courrier dans un délai de 7 jours après l'entretien" },
    ],
    profilesTitle: "Profils admissibles",
    profiles: [
      { title: "Accès en 1ère année", description: "Bac Scientifique, Économique et Technique" },
      { title: "Accès en 2ème année", description: "CPGE, Math Spé, EST, BTS, DUT ou Diplôme Équivalent" },
      { title: "Accès en M1", description: "Licence en Informatique ou Diplôme Équivalent" },
    ],
    datesTitle: "Dates importantes",
    dates: [
      { date: "1er Décembre - 30 Avril", description: "Période de dépôt des candidatures pour l'année académique suivante" },
      { date: "Mai - Juin", description: "Sessions d'entretiens et tests d'admission" },
      { date: "15 Juillet", description: "Date limite de confirmation d'inscription pour les candidats admis" },
      { date: "Septembre", description: "Rentrée académique et semaine d'intégration" },
    ],
    contactTitle: "Besoin d'informations supplémentaires ?",
    contacts: [
      { icon: "mail", text: "info@esisa.ac.ma" },
      { icon: "phone", text: "+212 (0)5 35 65 70 95" },
      { icon: "location-on", text: "29 Bis Av Ibn Khatib Route d’Imouzzer, Fès-Maroc" },
    ],
    applyNow: "POSTULER MAINTENANT",
    internationalTitle: "L'ESISA ET L'INTERNATIONAL",
    internationalIntro:
      "🚀 Une formation tournée vers l’international : L'ESISA ouvre à ses étudiants les portes d’une carrière mondiale grâce à ses partenariats avec des institutions de renom en France, aux États-Unis et au-delà. Nos programmes sont conçus pour offrir une expérience académique et professionnelle enrichissante.",
    internationalStagesTitle: "📅 STAGES À L'ÉTRANGER",
    internationalStagesDesc:
      "- 3ème année : Stage de 2 à 3 mois dans des entreprises partenaires.\n- 5ème année : Stage de 4 à 6 mois dans des secteurs innovants.",
    internationalSkillsTitle: "🧠 COMPÉTENCES LINGUISTIQUES",
    internationalSkillsDesc:
      "- Préparation avancée au TOEIC pour une maîtrise de l’anglais professionnel.\n- Certification B2/C1 en français grâce à notre partenariat avec l’Institut Français.",
    internationalCareersTitle: "🌍 CARRIÈRES GLOBALES",
    internationalCareersDesc:
      "Chaque année, nos étudiants poursuivent leurs études dans des établissements de prestige ou débutent leur carrière dans des environnements internationaux.\nPour l’année universitaire 2025/2026, 95% de nos étudiants de master 1 IS2IA ont intégré des masters dans des universités prestigieuses et des écoles d’ingénieurs d’État en France.",
    internationalAdmittedTitle: "🌎 ADMIS À L'ÉTRANGER",
    internationalAdmittedDesc:
      "Chaque année, une grande partie des étudiants de la 4ème année continuent leurs études en France, soit avec nos partenaires, soit dans d'autres universités étrangères.\nL’année universitaire 2024/2025, 95% des étudiants ont été acceptés dans nos universités et écoles partenaires.",
    internationalPartnersTitle: "NOS PARTENAIRES EN FRANCE",
    internationalAddressLabel: "ADRESSE",
    internationalAddress: "29 Bis Av Ibn Khatib Route d’Imouzzer, Fès-Maroc",
    internationalPhoneLabel: "TÉLÉPHONE",
    internationalPhone: "+212 (0)5 35 65 70 95",
    internationalEmailLabel: "EMAIL",
    internationalEmail: "info@esisa.ac.ma",

     coursesTitle: "Nos Formations",
    coursesIntro: "L'enseignement à l'école ESISA est fondé sur un fonctionnement par semestre, basé sur le système modulaire. À l'école ESISA, l'enseignement est dispensé en 2 cycles étalés sur 5 années d'études.",
    firstCycleTitle: "1er Cycle (Bac +3 ans)",
    years12Title: "1ère et 2ème années",
    years12Description: "L'objectif est d'initier l'étudiant aux domaines de l'informatique avec ses différentes disciplines, et de développer ses compétences en développement informatique à travers une formation centrée sur:",
    years12Subjects: [
      "Programmation",
      "Structures de données",
      "Langages de programmation",
      "Bases de données",
      "Systèmes d'information",
      "Réseaux informatiques"
    ],
    year3Title: "3ème année",
    year3Description: "L'objectif est de former des assistants débutants à la maîtrise d'œuvre (MOE) et à la maîtrise d'ouvrage (MO), dans les domaines de la conception et de l'administration des systèmes d'information:",
    year3Subjects: [
      "Bases de données",
      "Réseaux",
      "Architecture technique",
      "Développement d'applications",
      "Déploiement logiciel",
      "Intégration d'exploitation",
      "Analyse et traitements statistiques"
    ],
    secondCycleTitle: "2ème Cycle (2 ans après Bac +3)",
    years45Title: "4ème et 5ème années",
    years45Description1: "Ce cycle comprend 2 années d'études. Il a pour objectif principal de faire évoluer les compétences de l'étudiant vers la maîtrise des grands systèmes et leurs architectures, avec une grande expérience théorique et technique dans le domaine du développement basé sur les nouvelles technologies informatiques.",
    years45Description2: "Il se clôt par la réalisation d'un projet de fin d'études dans le secteur industriel, mené principalement au sein des entreprises actives dans le développement informatique à l'échelle internationale et dans le domaine du développement offshore.",
    years45Description3: "Options disponibles:",
    years45Options: [
      "M1 et M2 à l'ESISA",
      "M2 dans des universités étatiques en France suite au M1 à l'ESISA",
      "Diplôme d'Ingénieur d'état en France (2 ans)"
    ],
    languageSectionTitle: "Importance des langues",
    languageSectionDesc1: "L'école ESISA met l'accent sur l'importance de la communication en français et en anglais dans les métiers de l'ingénierie. Tout au long des années d'études, les étudiants sont préparés à une meilleure adaptation linguistique pour faciliter leur intégration dans les cursus finaux à l'étranger et ouvrir les portes des métiers de l'avenir.",
    languageSectionDesc2: "En outre, les entretiens de sélection pour les différentes écoles et universités partenaires se passent en français et en anglais. Les étudiants de l'ESISA sont appelés à atteindre le niveau de TOEIC (Test Of English for International Communication) en fin de 4ème année.",
  


  error: "Erreur",
  documentSelectError: "Impossible de sélectionner le document",
  enterNamePrenom: "Veuillez saisir votre nom et prénom",
  enterValidEmail: "Veuillez saisir une adresse email valide",
  enterValidPhone: "Veuillez saisir un numéro de téléphone valide (format marocain)",
  enterBirthdate: "Veuillez saisir votre date de naissance",
  selectNiveau: "Veuillez sélectionner le niveau d'entrée souhaité",
  enterBacNotes: "Veuillez saisir vos notes de mathématiques et de français au baccalauréat",
  attachCin: "Veuillez joindre une copie de votre CIN",
  attachRelevesBac: "Veuillez joindre vos relevés de notes du baccalauréat",
  attachPhoto: "Veuillez joindre une photo d'identité récente",
  sendError: "Une erreur est survenue lors de l'envoi.",
  submitFormError: "Une erreur est survenue lors de l'envoi de votre candidature. Veuillez réessayer ultérieurement.",
  applicationFormTitle: "FORMULAIRE DE CANDIDATURE",
  applicationFormIntro: "Complétez ce formulaire pour soumettre votre candidature à l'ESISA",
  personalInformation: "Informations Personnelles",
  lastName: "Nom",
  firstName: "Prénom",
  email: "Email",
  phone: "Téléphone",
  birthDate: "Date de naissance",
  address: "Adresse",
  city: "Ville",
  academicInformation: "Informations Académiques",
  desiredLevel: "Niveau d'entrée souhaité",
  selectLevelPlaceholder: "Sélectionnez un niveau...",
  firstYear: "1ère année",
  secondYear: "2ème année",
  thirdYear: "3ème année",
  master1: "Master 1 (M1)",
  master2: "Master 2 (M2)",
  fieldOfStudy: "Filière (si applicable)",
  enterFieldOfStudy: "Filière souhaitée",
  mathBac: "Note en Mathématiques au Bac",
  enterMathNote: "Votre note en mathématiques",
  frenchBac: "Note en Français au Bac",
  enterFrenchNote: "Votre note en français",
  generalAvgBac: "Moyenne générale au Bac",
  enterGeneralAvg: "Votre moyenne générale",
  requiredDocuments: "Documents Requis",
  cinCopy: "Copie de la CIN (recto/verso)",
  cinDesc: "Format PDF ou image (max 5 Mo)",
  bacRecords: "Relevés de notes du Bac",
  bacRecordsDesc: "Format PDF ou image (max 5 Mo)",
  recentPhoto: "Photo d'identité récente",
  recentPhotoDesc: "Format JPEG ou PNG (max 2 Mo)",
  modify: "Modifier",
  choose: "Choisir",
  fileSelected: "Fichier sélectionné",
  motivationLetter: "Lettre de Motivation",
  motivationPlaceholder: "Expliquez brièvement votre motivation à rejoindre l'ESISA (min. 100 caractères)",
  submitApplication: "ENVOYER MA CANDIDATURE",
  mandatoryFields: "* Champs obligatoires",
  applicationSent: "Candidature Envoyée !",
  applicationSentDesc: "Votre candidature a été envoyée avec succès. Nous vous contacterons prochainement.",
  laboratory: {
      title: "ESISA ANALYTICA",
      description: "Bienvenue dans notre laboratoire, où l'innovation et la recherche sont au cœur de nos activités.",
      watchVideos: "Regarder les vidéos",
      videoTitle: "Présentation Vidéo du Laboratoire",
      explanation: "Nos recherches",
      details: "Découvrez nos projets et collaborations à travers des vidéos immersives.",

    },

    chat_with_einstein: "Chattez avec Einstein",
    ask_einstein: "Posez votre question à Einstein...",
    send: "Envoyer",
    einstein_response_error: "Désolé, je n'ai pas pu obtenir de réponse.",
    einstein_connection_error: "Erreur de connexion à Einstein.",

    welcome: "Bienvenue", // Ajout de la traduction pour le message de bienvenue
    profileInfo: "Informations du profil",
    profileTitle: "Informations du Profil",
    age: "Âge :",
    major: "Spécialité :",
    schoolYear: "Année scolaire :",
    group: "Groupe :",
    gender: "Genre :",
   logout: "Se déconnecter",




    form: "Formulaire de Candidature",
    form_intro: "Veuillez remplir le formulaire ci-dessous pour soumettre votre candidature.",
    personal_information: "Informations Personnelles",
    last_name: "Nom",
    first_name: "Prénom",
    birth_date: "Date de naissance",
    academic_information: "Informations Académiques",
    desired_level: "Niveau désiré",
    field_of_study: "Filière",
    math_bac: "Note en Mathématiques (Baccalauréat)",
    french_bac: "Note en Français (Baccalauréat)",
    general_avg_bac: "Moyenne générale (Baccalauréat)",
    required_documents: "Documents requis",
    cin_copy: "Copie de CIN",
    bac_records: "Relevés de Baccalauréat",
    recent_photo: "Photo récente",
    motivation_letter: "Lettre de motivation",
    submit_application: "Soumettre la candidature",
    file_selected: "Fichier sélectionné",
    mandatory_fields: "* Champs obligatoires",
    application_sent: "Candidature envoyée !",
    application_sent_desc: "Votre candidature a été envoyée avec succès.",
    document_select_error: "Impossible de sélectionner le document",
    enter_name_prenom: "Veuillez entrer votre nom et prénom",
    enter_valid_email: "Veuillez entrer une adresse email valide",
    enter_valid_phone: "Veuillez entrer un numéro de téléphone valide",
    enter_birthdate: "Veuillez entrer votre date de naissance",
    select_niveau: "Veuillez sélectionner le niveau souhaité",
    enter_bac_notes: "Veuillez entrer vos notes de mathématiques et de français au baccalauréat",
    attach_cin: "Veuillez joindre une copie de votre CIN",
    attach_releves_bac: "Veuillez joindre vos relevés de notes du baccalauréat",
    attach_photo: "Veuillez joindre une photo récente",
    send_error: "Une erreur est survenue lors de l'envoi.",
    submit_form_error: "Une erreur est survenue lors de l'envoi de votre candidature. Veuillez réessayer plus tard.",
  
    
    enter_last_name: "Entrez votre nom",
    enter_first_name: "Entrez votre prénom",
    enter_email: "Entrez votre email",
    enter_phone: "Entrez votre téléphone",
    enter_address: "Entrez votre adresse",
    enter_city: "Entrez votre ville",
    select_level: "Sélectionner le niveau",
    first_year: "Première année",
    second_year: "Deuxième année",
    third_year: "Troisième année",
    master_1: "Master 1",
    master_2: "Master 2",
    bac_notes: "Notes du Bac",
    math_note: "Note en mathématiques",
    french_note: "Note en français",
    average_note: "Moyenne générale",
    enter_field: "Entrez le champ",

    virtualExperience: "Expérience virtuelle à 360°",

     back: "Retour",
    chooseChannel: "Choisissez votre canal de discussion",
    userNotConnected: "Utilisateur non connecté",
    userLoadFail: "Impossible de charger l'utilisateur",
    channelGroup: "Canal : Groupe",
    channelYear: "Canal : Année",
    writeMessage: "Écrire un message...",


    labTitle: "ESISA ANALYTICA",
    labDescription: "Bienvenue dans notre laboratoire, où l'innovation et la recherche sont au cœur de nos activités.",
    researchTitle: "Nos Recherches",
    researchDescription: "Découvrez nos projets et collaborations à travers des vidéos immersives.",
    researchAreas: [
      { title: "Intelligence Artificielle", description: "Développement d'algorithmes avancés" },
      { title: "Analyse de Données", description: "Traitement et visualisation de données complexes" },
      { title: "Systèmes Embarqués", description: "Conception de solutions IoT innovantes" }
    ],
    videoTitle: "Vidéo de Présentation",
    equipmentTitle: "Nos Équipements",
    equipment: [
      { name: "Serveurs haute performance", description: "Pour le calcul intensif" },
      { name: "Stations de développement", description: "Environnements de développement avancés" },
      { name: "Laboratoire IoT", description: "Espace dédié aux objets connectés" }
    ],
    labContactTitle: "Contact Laboratoire",
    labContacts: [
      { icon: "email", text: "info@esisa.ac.ma" },
      { icon: "phone", text: "+212 5 35 65 70 95" },
      { icon: "location-on", text: "29 bis avenue Ibn Khatib, route D'imouzzer, Fès 30050" }
    ]

    

   
},

  
  
  
  en: {
    settings: "Settings",
    appearance: "Appearance",
    darkMode: "Dark Mode",
    language: "Language",
    admissionTitle: "ADMISSION PROCESS AND PROCEDURE",
    admissionIntro: "ESISA selects the best talents to train the elite in computer engineering.",
    admissionDescription1: "At ESISA, we believe that ",
    highlightMotivation: "motivation",
    and: "and",
    highlightPassion: "passion for digital technology",
    admissionDescription2: " are the driving forces of excellence. We look for determined students ready to shape tomorrow’s world through innovative technologies. Each application is carefully evaluated taking into account:",
    criteria: [
      { title: "Motivation and Ambition", description: "Your determination to succeed and innovate is essential." },
      { title: "Grades in Mathematics and French at the Bac", description: "Key indicators of success." },
      { title: "If grades are insufficient", description: "A Mathematics test is required." },
      { title: "Motivational Interview", description: "To assess your passion, goals, and vision." },
    ],
    admissionConclusion: "We favor engaged and motivated profiles capable of meeting tomorrow’s technological challenges.",
    processTitle: "Steps of the Admission Process",
    processSteps: [
      { title: "Submission of Application", description: "Completed registration form, copy of ID card, Bac transcripts, recent ID photo" },
      { title: "Academic File Review", description: "Analysis of grades in mathematics and French, verification of academic profile" },
      { title: "Aptitude Test (if necessary)", description: "Mathematics test for candidates whose Bac grades are insufficient" },
      { title: "Motivational Interview", description: "In-depth discussion about your goals, passion for computing, and vision for the digital future" },
      { title: "Admission Decision", description: "Notification by email and mail within 7 days after the interview" },
    ],
    profilesTitle: "Eligible Profiles",
    profiles: [
      { title: "Access to 1st Year", description: "Scientific, Economic, and Technical Bac" },
      { title: "Access to 2nd Year", description: "CPGE, Math Specialization, EST, BTS, DUT or Equivalent Diploma" },
      { title: "Access to M1", description: "Bachelor’s Degree in Computer Science or Equivalent Diploma" },
    ],
    datesTitle: "Important Dates",
    dates: [
      { date: "December 1 - April 30", description: "Application submission period for the following academic year" },
      { date: "May - June", description: "Interview and admission test sessions" },
      { date: "July 15", description: "Deadline for confirming registration for admitted candidates" },
      { date: "September", description: "Academic start and integration week" },
    ],
    contactTitle: "Need more information?",
    contacts: [
      { icon: "mail", text: "info@esisa.ac.ma" },
      { icon: "phone", text: "+212 (0)5 35 65 70 95" },
      { icon: "location-on", text: "29 Bis Ibn Khatib Avenue, Imouzzer Road, Fez, Morocco" },
    ],
    applyNow: "APPLY NOW",

    internationalTitle: "ESISA AND INTERNATIONAL",
    internationalIntro:
      "🚀 A globally oriented training: ESISA opens the doors of a worldwide career to its students thanks to partnerships with renowned institutions in France, the United States, and beyond. Our programs are designed to offer an enriching academic and professional experience.",
    internationalStagesTitle: "📅 INTERNSHIPS ABROAD",
    internationalStagesDesc:
      "- 3rd year: 2 to 3 months internship in partner companies.\n- 5th year: 4 to 6 months internship in innovative sectors.",
    internationalSkillsTitle: "🧠 LANGUAGE SKILLS",
    internationalSkillsDesc:
      "- Advanced TOEIC preparation for mastering professional English.\n- B2/C1 French certification thanks to our partnership with the Institut Français.",
    internationalCareersTitle: "🌍 GLOBAL CAREERS",
    internationalCareersDesc:
      "Every year, our students continue their studies at prestigious institutions or start their careers in international environments.\nFor the 2025/2026 academic year, 95% of our Master 1 IS2IA students joined master's programs at prestigious universities and state engineering schools in France.",
    internationalAdmittedTitle: "🌎 ADMITTED ABROAD",
    internationalAdmittedDesc:
      "Each year, a large part of 4th-year students continue their studies in France, either with our partners or in other foreign universities.\nIn the 2024/2025 academic year, 95% of students were accepted in our partner universities and schools.",
    internationalPartnersTitle: "OUR PARTNERS IN FRANCE",
    internationalAddressLabel: "ADDRESS",
    internationalAddress: "29 Bis Ibn Khatib Avenue, Imouzzer Road, Fez, Morocco",
    internationalPhoneLabel: "PHONE",
    internationalPhone: "+212 (0)5 35 65 70 95",
    internationalEmailLabel: "EMAIL",
    internationalEmail: "info@esisa.ac.ma",


     coursesTitle: "Our Courses",
    coursesIntro: "The teaching at ESISA is based on a semester system and modular courses. ESISA provides education in 2 cycles spread over 5 years.",
    firstCycleTitle: "First Cycle (Bac +3 years)",
    years12Title: "1st and 2nd Years",
    years12Description: "The goal is to introduce students to different fields of computer science and develop their skills in software development with training focused on:",
    years12Subjects: [
      "Programming",
      "Data Structures",
      "Programming Languages",
      "Databases",
      "Information Systems",
      "Computer Networks"
    ],
    year3Title: "3rd Year",
    year3Description: "The goal is to train beginner assistants in project management (MOE) and project ownership (MO) in the fields of design and administration of information systems:",
    year3Subjects: [
      "Databases",
      "Networks",
      "Technical Architecture",
      "Application Development",
      "Software Deployment",
      "Operation Integration",
      "Statistical Analysis and Processing"
    ],
    secondCycleTitle: "Second Cycle (2 years after Bac +3)",
    years45Title: "4th and 5th Years",
    years45Description1: "This cycle consists of 2 years of studies. Its main goal is to develop the student's skills towards mastering large systems and their architectures, with extensive theoretical and technical experience in development based on new IT technologies.",
    years45Description2: "It concludes with a final project mainly carried out within companies active in international software development and offshore development.",
    years45Description3: "Available options:",
    years45Options: [
      "M1 and M2 at ESISA",
      "M2 in state universities in France after M1 at ESISA",
      "State Engineering Degree in France (2 years)"
    ],
    languageSectionTitle: "Importance of Languages",
    languageSectionDesc1: "ESISA emphasizes the importance of communication in French and English in engineering professions. Throughout the years of study, students are prepared for better linguistic adaptation to facilitate integration in final courses abroad and open the doors to future professions.",
    languageSectionDesc2: "Additionally, the selection interviews for different partner schools and universities are conducted in French and English. ESISA students are expected to reach TOEIC (Test Of English for International Communication) level by the end of the 4th year.",
  
error: "Error",
  documentSelectError: "Unable to select the document",
  enterNamePrenom: "Please enter your last and first name",
  enterValidEmail: "Please enter a valid email address",
  enterValidPhone: "Please enter a valid phone number (Moroccan format)",
  enterBirthdate: "Please enter your birth date",
  selectNiveau: "Please select the desired entry level",
  enterBacNotes: "Please enter your math and French grades at the baccalaureate",
  attachCin: "Please attach a copy of your CIN",
  attachRelevesBac: "Please attach your baccalaureate transcripts",
  attachPhoto: "Please attach a recent ID photo",
  sendError: "An error occurred during submission.",
  submitFormError: "An error occurred while sending your application. Please try again later.",
  applicationFormTitle: "APPLICATION FORM",
  applicationFormIntro: "Fill in this form to submit your application to ESISA",
  personalInformation: "Personal Information",
  lastName: "Last Name",
  firstName: "First Name",
  email: "Email",
  phone: "Phone",
  birthDate: "Birth Date",
  address: "Address",
  city: "City",
  academicInformation: "Academic Information",
  desiredLevel: "Desired Entry Level",
  selectLevelPlaceholder: "Select a level...",
  firstYear: "1st Year",
  secondYear: "2nd Year",
  thirdYear: "3rd Year",
  master1: "Master 1 (M1)",
  master2: "Master 2 (M2)",
  fieldOfStudy: "Field of Study (if applicable)",
  enterFieldOfStudy: "Desired field of study",
  mathBac: "Math grade at Bac",
  enterMathNote: "Your math grade",
  frenchBac: "French grade at Bac",
  enterFrenchNote: "Your French grade",
  generalAvgBac: "General average at Bac",
  enterGeneralAvg: "Your general average",
  requiredDocuments: "Required Documents",
  cinCopy: "Copy of CIN (front/back)",
  cinDesc: "PDF or image format (max 5 MB)",
  bacRecords: "Bac transcripts",
  bacRecordsDesc: "PDF or image format (max 5 MB)",
  recentPhoto: "Recent ID photo",
  recentPhotoDesc: "JPEG or PNG format (max 2 MB)",
  modify: "Modify",
  choose: "Choose",
  fileSelected: "File selected",
  motivationLetter: "Motivation Letter",
  motivationPlaceholder: "Briefly explain your motivation to join ESISA (min. 100 characters)",
  submitApplication: "SUBMIT MY APPLICATION",
  mandatoryFields: "* Mandatory fields",
  applicationSent: "Application Sent!",
  applicationSentDesc: "Your application has been sent successfully. We will contact you soon.",

  laboratory: {
      title: "ESISA ANALYTICA",
      description: "Welcome to our laboratory, where innovation and research are at the heart of our activities.",
      watchVideos: "Watch Videos",
      videoTitle: "Laboratory Video Presentation",
      explanation: "Our Research",
      details: "Explore our projects and collaborations through immersive videos.",
    },

   

     chat_with_einstein: "Chat with Einstein",
    ask_einstein: "Ask your question to Einstein...",
    send: "Send",
    einstein_response_error: "Einstein didn't respond correctly.",
    einstein_connection_error: "Error connecting to Einstein.",
     welcome: "Welcome", 
    profileInfo: "Profile Information",




    form: "Application Form",
    form_intro: "Please fill out the form below to submit your application.",
    personal_information: "Personal Information",
    last_name: "Last Name",
    first_name: "First Name",
    academic_information: "Academic Information",
    desired_level: "Desired Level",
    field_of_study: "Field of Study",
    math_bac: "Math Score (Baccalaureate)",
    french_bac: "French Score (Baccalaureate)",
    general_avg_bac: "General Average (Baccalaureate)",
    required_documents: "Required Documents",
    cin_copy: "CIN Copy",
    bac_records: "Baccalaureate Records",
    recent_photo: "Recent Photo",
    motivation_letter: "Motivation Letter",
    submit_application: "Submit Application",
    file_selected: "File Selected",
    mandatory_fields: "* Mandatory Fields",
    application_sent: "Application Sent!",
    application_sent_desc: "Your application has been successfully sent.",
    document_select_error: "Failed to select the document",
    enter_name_prenom: "Please enter your first and last name",
    enter_valid_email: "Please enter a valid email address",
    enter_valid_phone: "Please enter a valid phone number",
    enter_birthdate: "Please enter your birthdate",
    select_niveau: "Please select the desired level",
    enter_bac_notes: "Please enter your math and French Baccalaureate grades",
    attach_cin: "Please attach a copy of your CIN",
    attach_releves_bac: "Please attach your Baccalaureate records",
    attach_photo: "Please attach a recent photo",
    send_error: "An error occurred while sending.",
    submit_form_error: "An error occurred while submitting the form. Please try again later.",

    enter_last_name: "Enter your last name",
    enter_first_name: "Enter your first name",
    enter_email: "Enter your email",
    enter_phone: "Enter your phone number",
    enter_address: "Enter your address",
    enter_city: "Enter your city",
    select_level: "Select level",
    first_year: "First year",
    second_year: "Second year",
    third_year: "Third year",
    master_1: "Master 1",
    master_2: "Master 2",
    bac_notes: "Bac marks",
    math_note: "Mathematics grade",
    french_note: "French grade",
    average_note: "Overall average",
    enter_field: "Enter the field",
    virtualExperience: "Virtual experience at 360°",

    back: "Back",
    chooseChannel: "Choose your chat channel",
    group: "Group",
    schoolYear: "School Year",
    userNotConnected: "User not connected",
    userLoadFail: "Failed to load user",

     channelGroup: "Channel: Group",
    channelYear: "Channel: Year",
    writeMessage: "Write a message...",

      labTitle: "ESISA ANALYTICA",
    labDescription: "Welcome to our lab, where innovation and research are at the heart of our activities.",
    researchTitle: "Our Research",
    researchDescription: "Explore our projects and collaborations through immersive videos.",
    researchAreas: [
      { title: "Artificial Intelligence", description: "Development of advanced algorithms" },
      { title: "Data Analysis", description: "Processing and visualizing complex data" },
      { title: "Embedded Systems", description: "Designing innovative IoT solutions" }
    ],
    videoTitle: "Presentation Video",
    equipmentTitle: "Our Equipment",
    equipment: [
      { name: "High-performance servers", description: "For intensive computation" },
      { name: "Development workstations", description: "Advanced development environments" },
      { name: "IoT Lab", description: "Dedicated space for connected objects" }
    ],
    labContactTitle: "Lab Contact",
    labContacts: [
      { icon: "email", text: "info@esisa.ac.ma" },
      { icon: "phone", text: "+212 5 35 65 70 95" },
      { icon: "location-on", text: "29 bis avenue Ibn Khatib, route D'imouzzer, Fès 30050" }
    ]
  
  },









   ar: {
    settings: "الإعدادات",
    appearance: "المظهر",
    darkMode: "الوضع المظلم",
    language: "اللغة",
    admissionTitle: "عملية وإجراءات القبول",
    admissionIntro: "تختار ESISA أفضل المواهب لتدريب النخبة في الهندسة المعلوماتية.",
    admissionDescription1: "في ESISA نعتقد أن ",
    highlightMotivation: "الدافع",
    and: "و",
    highlightPassion: "الشغف بالتكنولوجيا الرقمية",
    admissionDescription2: " هما محركا التميز. نحن نبحث عن الطلاب الملتزمين، المستعدين لتشكيل عالم الغد من خلال التقنيات المبتكرة...",
    criteria: [
      { title: "الدافع والطموح", description: "إصرارك على النجاح والابتكار أمر بالغ الأهمية." },
      { title: "العلامات في الرياضيات والفرنسية في الباكالوريا", description: "مؤشرات رئيسية للنجاح." },
      { title: "إذا كانت العلامات غير كافية", description: "يجب إجراء اختبار في الرياضيات." },
      { title: "مقابلة تحفيزية", description: "لتقييم شغفك وأهدافك ورؤيتك." },
    ],
    admissionConclusion: "نحن نفضل الملفات الشخصية الملتزمة والمتحمسة، القادرة على مواجهة تحديات التكنولوجيا في المستقبل.",
    processTitle: "خطوات عملية القبول",
    processSteps: [
      { title: "تقديم الملف", description: "استمارة التسجيل مكتملة، نسخة من بطاقة الهوية، كشوف الدرجات من الباكالوريا، صورة شخصية حديثة" },
      { title: "دراسة الملف الأكاديمي", description: "تحليل الدرجات في الرياضيات والفرنسية، التحقق من الملف الأكاديمي" },
      { title: "اختبار الكفاءة (إذا لزم الأمر)", description: "اختبار رياضيات للمرشحين الذين لا تكفي علاماتهم في الباكالوريا" },
      { title: "مقابلة تحفيزية", description: "مناقشة متعمقة حول أهدافك، شغفك بالحوسبة ورؤيتك لمستقبل رقمي" },
      { title: "قرار القبول", description: "الإخطار عبر البريد الإلكتروني والبريد العادي في غضون 7 أيام بعد المقابلة" },
    ],
    profilesTitle: "الملفات الشخصية المؤهلة",
    profiles: [
      { title: "الدخول إلى السنة الأولى", description: "باكالوريا علمية، اقتصادية وتقنية" },
      { title: "الدخول إلى السنة الثانية", description: "CPGE، رياضيات خاصة، EST، BTS، DUT أو شهادة معادلة" },
      { title: "الدخول إلى M1", description: "درجة البكالوريوس في علوم الكمبيوتر أو شهادة معادلة" },
    ],
    datesTitle: "التواريخ المهمة",
    dates: [
      { date: "1 ديسمبر - 30 أبريل", description: "فترة تقديم الطلبات للسنة الأكاديمية التالية" },
      { date: "مايو - يونيو", description: "جلسات المقابلات واختبارات القبول" },
      { date: "15 يوليو", description: "الموعد النهائي لتأكيد التسجيل للمرشحين المقبولين" },
      { date: "سبتمبر", description: "بداية السنة الأكاديمية وأسبوع التكامل" },
    ],
    contactTitle: "هل تحتاج إلى مزيد من المعلومات؟",
    contacts: [
      { icon: "mail", text: "info@esisa.ac.ma" },
      { icon: "phone", text: "+212 (0)5 35 65 70 95" },
      { icon: "location-on", text: "29 Bis شارع ابن الخطيب، طريق إيموزار، فاس، المغرب" },
    ],
    applyNow: "قدم الآن",
    profileTitle: "معلومات الحساب",
    email: "البريد الإلكتروني :",
    age: "العمر :",
    major: "التخصص :",
    schoolYear: "السنة الدراسية :",
    birthDate: "تاريخ الميلاد :",
    group: "المجموعة :",
    gender: "الجنس :",
    phone: "الهاتف :",
    logout: "تسجيل الخروج",

     coursesTitle: "دوراتنا",
    coursesIntro: "التعليم في مدرسة ESISA يعتمد على نظام فصول دراسية ونظام وحدات. تقدم ESISA التعليم في دورتين دراسيتين موزعتين على 5 سنوات.",
    firstCycleTitle: "الدورة الأولى (بكالوريا +3 سنوات)",
    years12Title: "السنة الأولى والثانية",
    years12Description: "الهدف هو إدخال الطالب في مجالات علوم الكمبيوتر وتطوير مهاراته في تطوير البرمجيات من خلال تدريب موجه نحو:",
    years12Subjects: [
      "البرمجة",
      "هياكل البيانات",
      "لغات البرمجة",
      "قواعد البيانات",
      "أنظمة المعلومات",
      "الشبكات الحاسوبية"
    ],
    year3Title: "السنة الثالثة",
    year3Description: "الهدف هو تدريب المساعدين المبتدئين في إدارة المشاريع (MOE) وملكية المشاريع (MO) في مجالات تصميم وإدارة أنظمة المعلومات:",
    year3Subjects: [
      "قواعد البيانات",
      "الشبكات",
      "الهندسة التقنية",
      "تطوير التطبيقات",
      "نشر البرمجيات",
      "تكامل التشغيل",
      "التحليل والمعالجة الإحصائية"
    ],
    secondCycleTitle: "الدورة الثانية (2 سنوات بعد بكالوريا +3)",
    years45Title: "السنة الرابعة والخامسة",
    years45Description1: "يتكون هذا الدورة من سنتين دراسيتين. الهدف الرئيسي هو تطوير مهارات الطالب نحو اتقان الأنظمة الكبيرة وعمارتها، مع تجربة نظرية وتقنية كبيرة في مجال التطوير باستخدام تقنيات الحوسبة الحديثة.",
    years45Description2: "تنتهي هذه الدورة بتنفيذ مشروع التخرج والذي يتم في الغالب داخل الشركات العاملة في تطوير البرمجيات على مستوى عالمي وفي مجال تطوير البرمجيات offshore.",
    years45Description3: "الخيارات المتاحة:",
    years45Options: [
      "M1 و M2 في ESISA",
      "M2 في الجامعات الحكومية في فرنسا بعد M1 في ESISA",
      "دبلوم مهندس دولة في فرنسا (سنتان)"
    ],
    languageSectionTitle: "أهمية اللغات",
    languageSectionDesc1: "تولي ESISA أهمية كبيرة للتواصل باللغتين الفرنسية والإنجليزية في وظائف الهندسة. طوال سنوات الدراسة، يتم تحضير الطلاب للتكيف اللغوي الأفضل لسهولة الاندماج في الدورات النهائية في الخارج وفتح الأبواب لمهن المستقبل.",
    languageSectionDesc2: "بالإضافة إلى ذلك، تتم مقابلات الاختيار للمدارس والجامعات الشريكة باللغتين الفرنسية والإنجليزية. يُتوقع من طلاب ESISA أن يصلوا إلى مستوى TOEIC (اختبار الإنجليزية للتواصل الدولي) بنهاية السنة الرابعة.",
  
    internationalTitle: "إيسيسا والعالمية",
    internationalIntro:
      "🚀 التعليم الموجه نحو العالمية: يفتح برنامج إيسيسا أمام طلابها أبواب مهنة عالمية بفضل شراكاتها مع مؤسسات مرموقة في فرنسا، الولايات المتحدة، وأكثر. برامجنا مصممة لتقديم تجربة أكاديمية ومهنية غنية.",
    internationalStagesTitle: "📅 التدريبات في الخارج",
    internationalStagesDesc:
      "- السنة 3: تدريب من 2 إلى 3 أشهر في شركات شريكة.\n- السنة 5: تدريب من 4 إلى 6 أشهر في قطاعات مبتكرة.",
    internationalSkillsTitle: "🧠 المهارات اللغوية",
    internationalSkillsDesc:
      "- التحضير المتقدم لاختبار TOEIC لإتقان اللغة الإنجليزية المهنية.\n- شهادة B2/C1 في اللغة الفرنسية بفضل شراكتنا مع المعهد الفرنسي.",
    internationalCareersTitle: "🌍 المهن العالمية",
    internationalCareersDesc:
      "كل عام، يواصل طلابنا دراستهم في مؤسسات مرموقة أو يبدأون حياتهم المهنية في بيئات دولية.\nفي العام الأكاديمي 2025/2026، 95% من طلاب الماجستير IS2IA انضموا إلى برامج ماجستير في جامعات مرموقة ومدارس هندسية حكومية في فرنسا.",
    internationalAdmittedTitle: "🌎 القبول في الخارج",
    internationalAdmittedDesc:
      "كل عام، يستمر جزء كبير من طلاب السنة الرابعة في دراستهم في فرنسا، إما مع شركائنا أو في جامعات أجنبية أخرى.\nفي العام الأكاديمي 2024/2025، تم قبول 95% من الطلاب في جامعات ومدارس شريكة.",
    internationalPartnersTitle: "شركاؤنا في فرنسا",
    internationalAddressLabel: "العنوان",
    internationalAddress: "29 Bis Av Ibn Khatib Route d’Imouzzer، فاس - المغرب",
    internationalPhoneLabel: "الهاتف",
    internationalPhone: "+212 (0)5 35 65 70 95",
    internationalEmailLabel: "البريد الإلكتروني",
    internationalEmail: "info@esisa.ac.ma",
    
    chat_with_einstein: "الدردشة مع أينشتاين",
    ask_einstein: "اسأل سؤالك عن أينشتاين...",
    send: "إرسال",
    einstein_response_error: "أينشتاين لم يرد بشكل صحيح.",
    einstein_connection_error: "خطأ في الاتصال مع أينشتاين.",
    welcome: "أهلاً وسهلاً", 
    profileInfo: "معلومات الملف الشخصي",


     form: "استمارة التقديم",
    form_intro: "يرجى ملء النموذج أدناه لإرسال طلبك.",
    personal_information: "المعلومات الشخصية",
    last_name: "الاسم الأخير",
    first_name: "الاسم الأول",
    birth_date: "تاريخ الميلاد",
    address: "العنوان",
    city: "المدينة",
    academic_information: "المعلومات الأكاديمية",
    desired_level: "المستوى المطلوب",
    field_of_study: "التخصص",
    math_bac: "درجة الرياضيات (البكالوريا)",
    french_bac: "درجة اللغة الفرنسية (البكالوريا)",
    general_avg_bac: "المعدل العام (البكالوريا)",
    required_documents: "الوثائق المطلوبة",
    cin_copy: "نسخة من البطاقة الوطنية",
    bac_records: "كشف درجات البكالوريا",
    recent_photo: "صورة حديثة",
    motivation_letter: "رسالة الدافع",
    submit_application: "إرسال الطلب",
    file_selected: "الملف المحدد",
    modify: "تعديل",
    choose: "اختيار",
    mandatory_fields: "* الحقول الإلزامية",
    application_sent: "تم إرسال الطلب!",
    application_sent_desc: "تم إرسال طلبك بنجاح.",
    error: "خطأ",
    document_select_error: "فشل في اختيار المستند",
    enter_name_prenom: "يرجى إدخال الاسم الأول والاسم الأخير",
    enter_valid_email: "يرجى إدخال عنوان بريد إلكتروني صالح",
    enter_valid_phone: "يرجى إدخال رقم هاتف صالح",
    enter_birthdate: "يرجى إدخال تاريخ الميلاد",
    select_niveau: "يرجى اختيار المستوى المطلوب",
    enter_bac_notes: "يرجى إدخال درجات الرياضيات والفرنسية في البكالوريا",
    attach_cin: "يرجى إرفاق نسخة من البطاقة الوطنية",
    attach_releves_bac: "يرجى إرفاق كشف درجات البكالوريا",
    attach_photo: "يرجى إرفاق صورة حديثة",
    send_error: "حدث خطأ أثناء الإرسال.",
    submit_form_error: "حدث خطأ أثناء إرسال طلبك. يرجى المحاولة مرة أخرى لاحقاً.",


     enter_last_name: "أدخل اسم العائلة",
    enter_first_name: "أدخل الاسم الأول",
    enter_email: "أدخل بريدك الإلكتروني",
    enter_phone: "أدخل رقم هاتفك",
    enter_address: "أدخل عنوانك",
    enter_city: "أدخل مدينتك",
    select_level: "حدد المستوى",
    first_year: "السنة الأولى",
    second_year: "السنة الثانية",
    third_year: "السنة الثالثة",
    master_1: "الماجستير 1",
    master_2: "الماجستير 2",
    bac_notes: "درجات البكالوريا",
    math_note: "درجة الرياضيات",
    french_note: "درجة الفرنسية",
    average_note: "المعدل العام",
    enter_field: "أدخل الحقل",
    virtualExperience: "تجربة افتراضية بزاوية 360°",

        back: "رجوع",
    chooseChannel: "اختر قناة المحادثة",
    userNotConnected: "المستخدم غير متصل",
    userLoadFail: "تعذر تحميل المستخدم",

    channelGroup: "القناة: المجموعة",
    channelYear: "القناة: السنة",
    writeMessage: "اكتب رسالة...",

    
     labTitle: "إيسيسا أناليتيكا",
    labDescription: "مرحبًا بكم في مختبرنا، حيث الابتكار والبحث في صميم أنشطتنا.",
    researchTitle: "أبحاثنا",
    researchDescription: "اكتشف مشاريعنا وتعاوناتنا من خلال مقاطع فيديو غامرة.",
    researchAreas: [
      { title: "الذكاء الاصطناعي", description: "تطوير خوارزميات متقدمة" },
      { title: "تحليل البيانات", description: "معالجة وعرض البيانات المعقدة" },
      { title: "الأنظمة المدمجة", description: "تصميم حلول إنترنت الأشياء المبتكرة" }
    ],
    videoTitle: "فيديو تقديمي",
    equipmentTitle: "معداتنا",
    equipment: [
      { name: "خوادم عالية الأداء", description: "للحوسبة المكثفة" },
      { name: "محطات تطوير", description: "بيئات تطوير متقدمة" },
      { name: "مختبر إنترنت الأشياء", description: "مساحة مخصصة للأشياء المتصلة" }
    ],
    labContactTitle: "اتصال المختبر",
    labContacts: [
      { icon: "email", text: "info@esisa.ac.ma" },
      { icon: "phone", text: "+212 5 35 65 70 95" },
      { icon: "location-on", text: "29 شارع ابن خطيب، طريق إموزار، فاس 30050" }
    ],


  
  },

  es: {
    settings: "Configuración",
    appearance: "Apariencia",
    darkMode: "Modo oscuro",
    language: "Idioma",
    admissionTitle: "PROCESO Y PROCEDIMIENTO DE ADMISIÓN",
    admissionIntro: "ESISA selecciona los mejores talentos para formar a la élite en ingeniería informática.",
    admissionDescription1: "En ESISA creemos que ",
    highlightMotivation: "la motivación",
    and: "y",
    highlightPassion: "la pasión por la tecnología digital",
    admissionDescription2: " son los motores de la excelencia. Buscamos estudiantes determinados, listos para dar forma al mundo del mañana a través de tecnologías innovadoras...",
    criteria: [
      { title: "Motivación y Ambición", description: "Tu determinación para tener éxito e innovar es esencial." },
      { title: "Notas en Matemáticas y Francés en el Bac", description: "Indicadores clave de éxito." },
      { title: "Si las notas son insuficientes", description: "Se requiere una prueba de Matemáticas." },
      { title: "Entrevista motivacional", description: "Para evaluar tu pasión, tus objetivos y tu visión." },
    ],
    admissionConclusion: "Priorizamos perfiles comprometidos y motivados, capaces de afrontar los desafíos tecnológicos del mañana.",
    processTitle: "Pasos del proceso de admisión",
    processSteps: [
      { title: "Envío de la solicitud", description: "Formulario de inscripción completo, copia de la CIN, expedientes del Bac, foto reciente" },
      { title: "Revisión del expediente académico", description: "Análisis de las notas en matemáticas y francés, verificación del perfil académico" },
      { title: "Prueba de aptitud (si es necesario)", description: "Prueba de matemáticas para los candidatos con notas insuficientes en el Bac" },
      { title: "Entrevista motivacional", description: "Discusión profunda sobre tus objetivos, tu pasión por la informática y tu visión del futuro digital" },
      { title: "Decisión de admisión", description: "Notificación por correo electrónico y postal dentro de los 7 días después de la entrevista" },
    ],
    profilesTitle: "Perfiles elegibles",
    profiles: [
      { title: "Acceso a 1er Año", description: "Bac Científico, Económico y Técnico" },
      { title: "Acceso a 2do Año", description: "CPGE, Especialización en Matemáticas, EST, BTS, DUT o Diploma Equivalente" },
      { title: "Acceso a M1", description: "Licenciatura en Informática o Diploma Equivalente" },
    ],
    datesTitle: "Fechas importantes",
    dates: [
      { date: "1 de diciembre - 30 de abril", description: "Período de presentación de solicitudes para el siguiente año académico" },
      { date: "Mayo - Junio", description: "Sesiones de entrevistas y pruebas de admisión" },
      { date: "15 de julio", description: "Fecha límite para confirmar la inscripción de los candidatos admitidos" },
      { date: "Septiembre", description: "Inicio académico y semana de integración" },
    ],
    contactTitle: "¿Necesitas más información?",
    contacts: [
      { icon: "mail", text: "info@esisa.ac.ma" },
      { icon: "phone", text: "+212 (0)5 35 65 70 95" },
      { icon: "location-on", text: "29 Bis Av. Ibn Khatib, Ruta de Imouzzer, Fez, Marruecos" },
    ],
    applyNow: "APLICAR AHORA",
     profileTitle: "INFORMACIÓN DE PERFIL",
    email: "Correo electrónico :",
    age: "Edad :",
    major: "Carrera :",
    schoolYear: "Año escolar :",
    birthDate: "Fecha de nacimiento :",
    group: "Grupo :",
    gender: "Sexo :",
    phone: "Teléfono :",
    logout: "CERRAR SESIÓN",
      coursesTitle: "Nuestros Cursos",
    coursesIntro: "La enseñanza en la escuela ESISA se basa en un sistema semestral y modular. ESISA proporciona educación en 2 ciclos distribuidos en 5 años.",
    firstCycleTitle: "Primer Ciclo (Bac +3 años)",
    years12Title: "1er y 2do Año",
    years12Description: "El objetivo es introducir al estudiante en los campos de la informática y desarrollar sus habilidades en el desarrollo de software con formación centrada en:",
    years12Subjects: [
      "Programación",
      "Estructuras de datos",
      "Lenguajes de programación",
      "Bases de datos",
      "Sistemas de información",
      "Redes informáticas"
    ],
    year3Title: "3er Año",
    year3Description: "El objetivo es formar asistentes principiantes en gestión de proyectos (MOE) y en propiedad de proyectos (MO) en los campos del diseño y la administración de sistemas de información:",
    year3Subjects: [
      "Bases de datos",
      "Redes",
      "Arquitectura técnica",
      "Desarrollo de aplicaciones",
      "Despliegue de software",
      "Integración de explotación",
      "Análisis y tratamiento estadístico"
    ],
    secondCycleTitle: "Segundo Ciclo (2 años después de Bac +3)",
    years45Title: "4to y 5to Año",
    years45Description1: "Este ciclo comprende 2 años de estudios. Su principal objetivo es desarrollar las competencias del estudiante hacia el dominio de los grandes sistemas y sus arquitecturas, con una gran experiencia teórica y técnica en el desarrollo basado en nuevas tecnologías informáticas.",
    years45Description2: "Finaliza con la realización de un proyecto de fin de estudios realizado principalmente en empresas activas en el desarrollo de software a nivel internacional y en el desarrollo offshore.",
    years45Description3: "Opciones disponibles:",
    years45Options: [
      "M1 y M2 en ESISA",
      "M2 en universidades estatales en Francia después del M1 en ESISA",
      "Diploma de Ingeniero de Estado en Francia (2 años)"
    ],
    languageSectionTitle: "Importancia de los Idiomas",
    languageSectionDesc1: "ESISA pone énfasis en la importancia de la comunicación en francés e inglés en las profesiones de ingeniería. A lo largo de los años de estudio, los estudiantes se preparan para una mejor adaptación lingüística para facilitar su integración en los cursos finales en el extranjero y abrir las puertas a las profesiones del futuro.",
    languageSectionDesc2: "Además, las entrevistas de selección para las diferentes escuelas y universidades asociadas se realizan en francés e inglés. Se espera que los estudiantes de ESISA alcancen el nivel TOEIC (Test Of English for International Communication) al final del 4to año.",
    
    internationalTitle: "ESISA Y EL INTERNACIONAL",
    internationalIntro:
      "🚀 Una formación orientada al internacional: ESISA abre a sus estudiantes las puertas de una carrera global gracias a sus asociaciones con instituciones de renombre en Francia, Estados Unidos y más allá. Nuestros programas están diseñados para ofrecer una experiencia académica y profesional enriquecedora.",
    internationalStagesTitle: "📅 PASANTÍAS EN EL EXTRANJERO",
    internationalStagesDesc:
      "- 3er año: Pasantía de 2 a 3 meses en empresas asociadas.\n- 5to año: Pasantía de 4 a 6 meses en sectores innovadores.",
    internationalSkillsTitle: "🧠 COMPETENCIAS LINGÜÍSTICAS",
    internationalSkillsDesc:
      "- Preparación avanzada para el TOEIC para dominar el inglés profesional.\n- Certificación B2/C1 en francés gracias a nuestra asociación con el Instituto Francés.",
    internationalCareersTitle: "🌍 CARRERAS GLOBALES",
    internationalCareersDesc:
      "Cada año, nuestros estudiantes continúan sus estudios en instituciones prestigiosas o comienzan su carrera en entornos internacionales.\nPara el año académico 2025/2026, el 95% de nuestros estudiantes de maestría IS2IA han ingresado a programas de maestría en universidades prestigiosas y escuelas de ingeniería estatales en Francia.",
    internationalAdmittedTitle: "🌎 ADMITIDOS EN EL EXTRANJERO",
    internationalAdmittedDesc:
      "Cada año, una gran parte de los estudiantes de 4to año continúa sus estudios en Francia, ya sea con nuestros socios o en otras universidades extranjeras.\nEn el año académico 2024/2025, el 95% de los estudiantes fueron aceptados en nuestras universidades y escuelas asociadas.",
    internationalPartnersTitle: "NUESTROS SOCIOS EN FRANCIA",
    internationalAddressLabel: "DIRECCIÓN",
    internationalAddress: "29 Bis Av Ibn Khatib Route d’Imouzzer, Fès-Marruecos",
    internationalPhoneLabel: "TELÉFONO",
    internationalPhone: "+212 (0)5 35 65 70 95",
    internationalEmailLabel: "CORREO ELECTRÓNICO",
    internationalEmail: "info@esisa.ac.ma",

     chat_with_einstein: "Charlar con Einstein",
    ask_einstein: "Haz tu pregunta a Einstein...",
    send: "Enviar",
    einstein_response_error: "Einstein no respondió correctamente.",
    einstein_connection_error: "Error de conexión con Einstein.",
    welcome: "Bienvenido", 
    profileInfo: "Información del perfil",

    form: "Formulario de Solicitud",
    form_intro: "Por favor complete el formulario a continuación para enviar su solicitud.",
    personal_information: "Información Personal",
    last_name: "Apellido",
    first_name: "Nombre",
    birth_date: "Fecha de nacimiento",
    address: "Dirección",
    city: "Ciudad",
    academic_information: "Información Académica",
    desired_level: "Nivel deseado",
    field_of_study: "Campo de estudio",
    math_bac: "Nota de Matemáticas (Bachillerato)",
    french_bac: "Nota de Francés (Bachillerato)",
    general_avg_bac: "Promedio general (Bachillerato)",
    required_documents: "Documentos requeridos",
    cin_copy: "Copia del CIN",
    bac_records: "Registros de Bachillerato",
    recent_photo: "Foto reciente",
    motivation_letter: "Carta de motivación",
    submit_application: "Enviar solicitud",
    file_selected: "Archivo seleccionado",
    modify: "Modificar",
    choose: "Elegir",
    mandatory_fields: "* Campos obligatorios",
    application_sent: "¡Solicitud enviada!",
    application_sent_desc: "Su solicitud ha sido enviada con éxito.",
    error: "Error",
    document_select_error: "No se pudo seleccionar el documento",
    enter_name_prenom: "Por favor ingrese su nombre y apellido",
    enter_valid_email: "Por favor ingrese una dirección de correo electrónico válida",
    enter_valid_phone: "Por favor ingrese un número de teléfono válido",
    enter_birthdate: "Por favor ingrese su fecha de nacimiento",
    select_niveau: "Por favor seleccione el nivel deseado",
    enter_bac_notes: "Por favor ingrese sus notas de matemáticas y francés en el bachillerato",
    attach_cin: "Por favor adjunte una copia de su CIN",
    attach_releves_bac: "Por favor adjunte sus registros de bachillerato",
    attach_photo: "Por favor adjunte una foto reciente",
    send_error: "Ocurrió un error al enviar.",
    submit_form_error: "Ocurrió un error al enviar su solicitud. Por favor intente nuevamente más tarde.",
  

    enter_last_name: "Introduce tu apellido",
    enter_first_name: "Introduce tu nombre",
    enter_email: "Introduce tu correo electrónico",
    enter_phone: "Introduce tu número de teléfono",
    enter_address: "Introduce tu dirección",
    enter_city: "Introduce tu ciudad",
    select_level: "Seleccionar nivel",
    first_year: "Primer año",
    second_year: "Segundo año",
    third_year: "Tercer año",
    master_1: "Máster 1",
    master_2: "Máster 2",
    bac_notes: "Notas del Bachillerato",
    math_note: "Nota en matemáticas",
    french_note: "Nota en francés",
    average_note: "Promedio general",
    enter_field: "Introduce el campo",
    virtualExperience: "Experiencia virtual a 360°",
     back: "Volver",
    chooseChannel: "Elige tu canal de conversación",
    userNotConnected: "Usuario no conectado",
    userLoadFail: "No se pudo cargar el usuario",
    channelGroup: "Canal: Grupo",
    channelYear: "Canal: Año",
    writeMessage: "Escribe un mensaje...",



      labTitle: "ESISA ANALYTICA",
    labDescription: "Bienvenido a nuestro laboratorio, donde la innovación y la investigación están en el centro de nuestras actividades.",
    researchTitle: "Nuestras Investigaciones",
    researchDescription: "Descubre nuestros proyectos y colaboraciones a través de vídeos inmersivos.",
    researchAreas: [
      { title: "Inteligencia Artificial", description: "Desarrollo de algoritmos avanzados" },
      { title: "Análisis de Datos", description: "Procesamiento y visualización de datos complejos" },
      { title: "Sistemas Embebidos", description: "Diseño de soluciones innovadoras de IoT" }
    ],
    videoTitle: "Vídeo de Presentación",
    equipmentTitle: "Nuestros Equipos",
    equipment: [
      { name: "Servidores de alto rendimiento", description: "Para cálculos intensivos" },
      { name: "Estaciones de desarrollo", description: "Entornos de desarrollo avanzados" },
      { name: "Laboratorio IoT", description: "Espacio dedicado a objetos conectados" }
    ],
    labContactTitle: "Contacto del Laboratorio",
    labContacts: [
      { icon: "email", text: "info@esisa.ac.ma" },
      { icon: "phone", text: "+212 5 35 65 70 95" },
      { icon: "location-on", text: "29 bis avenue Ibn Khatib, route D'imouzzer, Fès 30050" }
    ],

  },
  

  


  
};
export default translations;

